In [17]:
import pandas as pd


PATH = '../datasets/raw/raw_gaia.parquet'
df   = pd.read_parquet(PATH)

print(f'Shape  : {df.shape[0]:,} rows × {df.shape[1]} columns')
print(f'Columns: {df.columns.tolist()}')

Shape  : 165 rows × 7 columns
Columns: ['task_id', 'Question', 'Level', 'Final answer', 'file_name', 'file_path', 'Annotator Metadata']

In [19]:
df.head()

,id,query,answer,level,annotator_steps,annotator_tools,file_name,steps_num,tool_num,time_taken
0,c61d22de-5f6c-4958-a7f6-5e9707bd3466,A paper about AI regulation that was originall...,egalitarian,2,1. Go to arxiv.org and navigate to the Advance...,1. Web browser\n2. Image recognition tools (to...,,12,2,8
1,17b5a6a3-bc87-42e8-b0fb-6ab0781ef2cc,I’m researching species that became invasive a...,34689,2,1. Search the web for “finding nemo main chara...,1. Search engine\n2. Web browser,,10,2,5
2,04a04a9b-226c-43fd-b319-d5e89743676f,If we assume all articles published by Nature ...,41,2,1. Find how many articles were published in Na...,1. search engine\n2. calculator,,3,2,5
3,14569e28-c88c-43e4-8c32-097d35b9a67d,"In Unlambda, what exact charcter or text needs...",backtick,2,"1. Searched ""Unlambda syntax"" online (optional...",1. Web browser\n2. Search engine\n3. Unlambda ...,,6,3,15
4,e1fc63a2-da7a-432f-be78-7c4a95598703,If Eliud Kipchoge could maintain his record-ma...,17,1,1. Googled Eliud Kipchoge marathon pace to fin...,1. A web browser.\n2. A search engine.\n3. A c...,,4,3,20

In [45]:
PATH = '../datasets/processed/gaia.parquet'
df   = pd.read_parquet(PATH)

print(f'Shape  : {df.shape[0]:,} rows × {df.shape[1]} columns')
print(f'Columns: {df.columns.tolist()}')

Shape  : 165 rows × 10 columns
Columns: ['id', 'query', 'answer', 'level', 'annotator_steps', 'annotator_tools', 'file_name', 'steps_num', 'tool_num', 'time_taken']

In [8]:
PATH = '../datasets/raw/raw_swe_bench.parquet'
df   = pd.read_parquet(PATH)

print(f'Shape  : {df.shape[0]:,} rows × {df.shape[1]} columns')
print(f'Columns: {df.columns.tolist()}')

Shape  : 500 rows × 13 columns
Columns: ['repo', 'instance_id', 'base_commit', 'patch', 'test_patch', 'problem_statement', 'hints_text', 'created_at', 'version', 'FAIL_TO_PASS', 'PASS_TO_PASS', 'environment_setup_commit', 'difficulty']

In [46]:
PATH = '../datasets/processed/swe_bench.parquet'
df   = pd.read_parquet(PATH)

print(f'Shape  : {df.shape[0]:,} rows × {df.shape[1]} columns')
print(f'Columns: {df.columns.tolist()}')

Shape  : 500 rows × 12 columns
Columns: ['id', 'query', 'answer', 'repo', 'base_commit', 'version', 'hints_text', 'difficulty', 'created_at', 'FAIL_TO_PASS', 'PASS_TO_PASS', 'num_fail_to_pass']

In [21]:
df.head()

,id,query,answer,repo,base_commit,version,hints_text,difficulty,created_at,FAIL_TO_PASS,PASS_TO_PASS,num_fail_to_pass
0,astropy__astropy-12907,Modeling's `separability_matrix` does not comp...,diff --git a/astropy/modeling/separable.py b/a...,astropy/astropy,d16bfe05a744909de4b27f5875fe0d4ed41ce607,4.3,,15 min - 1 hour,2022-03-03T15:14:54Z,"[""astropy/modeling/tests/test_separable.py::te...","[""astropy/modeling/tests/test_separable.py::te...",2
1,astropy__astropy-13033,TimeSeries: misleading exception when required...,diff --git a/astropy/timeseries/core.py b/astr...,astropy/astropy,298ccb478e6bf092953bca67a3d29dc6c35f6752,4.3,The relevant code that produces the misleading...,15 min - 1 hour,2022-03-31T23:28:27Z,"[""astropy/timeseries/tests/test_sampled.py::te...","[""astropy/timeseries/tests/test_sampled.py::te...",1
2,astropy__astropy-13236,Consider removing auto-transform of structured...,diff --git a/astropy/table/table.py b/astropy/...,astropy/astropy,6ed769d58d89380ebaa1ef52b300691eefda8928,5.0,@mhvk - I'm happy to do this PR if you think i...,15 min - 1 hour,2022-05-09T14:16:30Z,"[""astropy/table/tests/test_mixin.py::test_ndar...","[""astropy/table/tests/test_mixin.py::test_attr...",2
3,astropy__astropy-13398,A direct approach to ITRS to Observed transfor...,diff --git a/astropy/coordinates/builtin_frame...,astropy/astropy,6500928dc0e57be8f06d1162eacc3ba5e2eff692,5.0,"cc @StuartLittlefair, @adrn, @eteq, @eerovaher...",1-4 hours,2022-06-24T15:22:11Z,"[""astropy/coordinates/tests/test_intermediate_...","[""astropy/coordinates/tests/test_intermediate_...",4
4,astropy__astropy-13453,ASCII table output to HTML does not support su...,diff --git a/astropy/io/ascii/html.py b/astrop...,astropy/astropy,19cc80471739bcb67b7e8099246b391c355023ee,5.0,Welcome to Astropy 👋 and thank you for your fi...,15 min - 1 hour,2022-07-14T10:04:40Z,"[""astropy/io/ascii/tests/test_html.py::test_wr...","[""astropy/io/ascii/tests/test_html.py::test_li...",1

In [10]:
PATH = '../datasets/raw/raw_mmlu_pro.parquet'
df   = pd.read_parquet(PATH)

print(f'Shape  : {df.shape[0]:,} rows × {df.shape[1]} columns')
print(f'Columns: {df.columns.tolist()}')

Shape  : 12,032 rows × 8 columns
Columns: ['question_id', 'question', 'options', 'answer', 'answer_index', 'cot_content', 'category', 'src']

In [43]:
PATH = '../datasets/processed/mmlu_pro.parquet'
df   = pd.read_parquet(PATH)

print(f'Shape  : {df.shape[0]:,} rows × {df.shape[1]} columns')
print(f'Columns: {df.columns.tolist()}')

Shape  : 12,032 rows × 9 columns
Columns: ['id', 'query', 'answer', 'answer_index', 'options', 'category', 'cot_content', 'src', 'cot_length']

In [44]:
df.head()

,id,query,answer,answer_index,options,category,cot_content,src,cot_length
0,70,"Typical advertising regulatory bodies suggest,...",I,8,"[Safe practices, Fear, Jealousy, Trivial, Unsa...",business,,ori_mmlu-business_ethics,0
1,71,Managers are entrusted to run the company in t...,F,5,"[Shareholders, Diligence, Self-interest, Share...",business,,ori_mmlu-business_ethics,0
2,72,There are two main issues associated with ____...,J,9,"[Down, Autonomy, Remuneration, Benefit, Down, ...",business,,ori_mmlu-business_ethics,0
3,73,_______ locate morality beyond the sphere of r...,C,2,"[Ethical egoism, Ethics of duty, Postmodern et...",business,,ori_mmlu-business_ethics,0
4,74,Some of key differences between Islamic finan...,G,6,"[Interest, Certain, Assured, Both tangible and...",business,,ori_mmlu-business_ethics,0

In [38]:
PATH = '../datasets/raw/math_hard_test.parquet'
df   = pd.read_parquet(PATH)

print(f'Shape  : {df.shape[0]:,} rows × {df.shape[1]} columns')
print(f'Columns: {df.columns.tolist()}')

Shape  : 1,324 rows × 4 columns
Columns: ['problem', 'level', 'type', 'solution']

In [29]:
df.head( )

,problem,level,type,solution
0,How many square units are in the region satisf...,Level 5,Algebra,The graph of the two inequalities is shown bel...
1,"When Lauren was born on January 1, 1990, her g...",Level 5,Algebra,"The annual interest rate is 7.5 percent, so ea..."
2,Chris labels every lattice point in the coordi...,Level 5,Algebra,"Consider the point $(x,y)$. Then, he labels th..."
3,An airplane climbs 100 feet during the first s...,Level 5,Algebra,"After $t$ seconds, the airplane's altitude (in..."
4,Define $f(x)=\frac{1+x}{1-x}$ and $g(x)=\frac{...,Level 5,Algebra,Define a new function $h(x)$ so that $h(x)=g(f...

In [34]:
df["solution"].iloc[5]

'Given that $(8,8)$ is on the graph of $y=\\frac 14f\\left(\\frac 12x\\right)$, we can substitute $8$ for both $x$ and $y$ in that equation to obtain $$8 = \\frac14f\\left(\\frac 12\\cdot 8\\right).$$We can rewrite this information as $$32 = f(4),$$which tells us that $(4,32)$ must be on the graph of $y=f(x)$. The sum of coordinates of this point is $\\boxed{36}$.'

In [39]:
PATH = '../datasets/processed/math_hard.parquet'
df   = pd.read_parquet(PATH)

print(f'Shape  : {df.shape[0]:,} rows × {df.shape[1]} columns')
print(f'Columns: {df.columns.tolist()}')

Shape  : 1,205 rows × 8 columns
Columns: ['id', 'query', 'answer', 'level', 'type', 'solution', 'solution_length', 'has_figure']

In [42]:
df["answer"].iloc[5]

'36'

In [87]:
import pandas as pd, json
from pathlib import Path

path = Path("../results/unified_baseline/gaia/vanilla/gpt_4o_mini")

df = pd.read_parquet(path / "responses.parquet")
with open(path / "metrics.json", "r") as f:
    metrics = json.load(f)

display(df.head())
print(metrics)

,query_id,dataset,modality,model,query,ground_truth,predicted_answer,is_correct,reasoning_trace,tool_trace,...,completion_tokens,total_tokens,cost_usd,latency_s,error_type,error_message,system_prompt_version,user_prompt_version,prompt_hash,metadata
0,c61d22de-5f6c-4958-a7f6-5e9707bd3466,gaia,vanilla,gpt-4o-mini,A paper about AI regulation that was originall...,egalitarian,egalitarian,True,None,None,...,2,316,0.000048,0.838,None,None,v1,v1,773001201f2f0beb3d3431c33c26071a0512ed29d12629...,"{'file_name': '', 'level': '2'}"
1,17b5a6a3-bc87-42e8-b0fb-6ab0781ef2cc,gaia,vanilla,gpt-4o-mini,I’m researching species that became invasive a...,34689,"33139, 33140, 33141, 33142, 33143",False,None,None,...,18,358,0.000062,0.761,None,None,v1,v1,f48fcd297c7a51e459b63da365ef37594a09e6e9149e53...,"{'file_name': '', 'level': '2'}"
2,04a04a9b-226c-43fd-b319-d5e89743676f,gaia,vanilla,gpt-4o-mini,If we assume all articles published by Nature ...,41,1,False,None,None,...,1,316,0.000048,0.458,None,None,v1,v1,1c22d075038e4ee0de19a99989f5357a8145d6569e5dd9...,"{'file_name': '', 'level': '2'}"
3,14569e28-c88c-43e4-8c32-097d35b9a67d,gaia,vanilla,gpt-4o-mini,"In Unlambda, what exact charcter or text needs...",backtick,g,False,None,None,...,1,331,0.000050,0.677,None,None,v1,v1,d1f356f10cd7e0211d06e2af56f2035a40f4610af766be...,"{'file_name': '', 'level': '2'}"
4,e1fc63a2-da7a-432f-be78-7c4a95598703,gaia,vanilla,gpt-4o-mini,If Eliud Kipchoge could maintain his record-ma...,17,2000,False,None,None,...,2,324,0.000049,0.482,None,None,v1,v1,496087b6bff571c6661c626862039b0fa33a41fbb9bcd5...,"{'file_name': '', 'level': '1'}"

{'dataset': 'gaia', 'modality': 'vanilla', 'model': 'gpt-4o-mini', 'system_prompt_version': 'v1', 'user_prompt_version': 'v1', 'prompt_hash': '773001201f2f0beb3d3431c33c26071a0512ed29d12629d073bc517fb37ff06b', 'total_queries': 50, 'correct_queries': 4, 'accuracy': 0.08, 'total_prompt_tokens': 15738, 'total_completion_tokens': 179, 'total_tokens': 15917, 'avg_tokens_per_query': 318.34, 'total_cost_usd': 0.00247, 'avg_latency_s': 0.576, 'p50_latency_s': 0.544, 'p95_latency_s': 0.767, 'error_count': 0, 'error_rate': 0.0, 'avg_reasoning_steps': None, 'avg_tool_calls': None, 'metadata': {'gaia_level_metrics': {'1': {'total': 14, 'correct': 1, 'accuracy': 0.071429}, '2': {'total': 29, 'correct': 3, 'accuracy': 0.103448}, '3': {'total': 7, 'correct': 0, 'accuracy': 0.0}}}}

In [50]:
import os
print(os.getcwd())

/Users/poorna/Desktop/research_work/notebooks

In [88]:
import pandas as pd
from pathlib import Path

path = Path("../results/unified_baseline/gaia/vanilla/gpt_4o_mini/responses.parquet")
df = pd.read_parquet(path)

# Overall accuracy
print("Accuracy:", df["is_correct"].mean())
print("Correct/Total:", int(df["is_correct"].sum()), "/", len(df))

# See correct rows
display(df[df["is_correct"] == True][["query_id","query","ground_truth","predicted_answer"]].head(20))

# See incorrect rows
display(df[df["is_correct"] == False][["query_id","query","ground_truth","predicted_answer"]].head(20))

Accuracy: 0.08
Correct/Total: 4 / 50

,query_id,query,ground_truth,predicted_answer
0,c61d22de-5f6c-4958-a7f6-5e9707bd3466,A paper about AI regulation that was originall...,egalitarian,egalitarian
25,e4e91f1c-1dcd-439e-9fdd-cb976f5293fd,I need to fact-check a citation. This is the c...,cloak,cloak
34,2d83110e-a098-4ebb-9987-066c06fa42d0,".rewsna eht sa ""tfel"" drow eht fo etisoppo eht...",Right,right
45,b9763138-c053-4832-9f55-86200cb1f99c,Compute the check digit the Tropicos ID for th...,3,3

,query_id,query,ground_truth,predicted_answer
1,17b5a6a3-bc87-42e8-b0fb-6ab0781ef2cc,I’m researching species that became invasive a...,34689,"33139, 33140, 33141, 33142, 33143"
2,04a04a9b-226c-43fd-b319-d5e89743676f,If we assume all articles published by Nature ...,41,1
3,14569e28-c88c-43e4-8c32-097d35b9a67d,"In Unlambda, what exact charcter or text needs...",backtick,g
4,e1fc63a2-da7a-432f-be78-7c4a95598703,If Eliud Kipchoge could maintain his record-ma...,17,2000
5,32102e3e-d12a-4209-9163-7b3a104efe5d,The attached spreadsheet shows the inventory f...,Time-Parking 2: Parallel Universe,Avatar
6,8e867cd7-cff9-4e6c-867a-ff5ddc2550be,How many studio albums were published by Merce...,3,four
7,3627a8be-a77f-41bb-b807-7e1bd4c0ebdf,The object in the British Museum's collection ...,142,100
8,7619a514-5fa8-43ef-9143-83b66a43d7a4,"According to github, when was Regression added...",04/15/18,09/29/20
9,ec09fa32-d03f-4bf8-84b0-1f16922c3ae4,Here's a fun riddle that I think you'll enjoy....,3,2
10,676e5e31-a554-4acc-9286-b60d90a92d26,"In July 2, 1959 United States standards for gr...",86,50%
11,7dd30055-0198-452e-8c25-f73dbe27dcb8,"Using the Biopython library in Python, parse t...",1.456,400
12,2a649bb1-795f-4a01-b3be-9a01868dae73,What are the EC numbers of the two most common...,3.1.3.1; 1.11.1.7,1.1.1.1; 1.1.1.2
13,87c610df-bef7-4932-b950-1d83ef4e282b,"In April of 1977, who was the Prime Minister o...",Morarji Desai,Ahasuerus
14,624cbf11-6a41-4692-af9c-36b3e5ca3130,What's the last line of the rhyme under the fl...,So we had to let it die.,"""Rest in peace"""
15,dd3c7503-f62a-4bd0-9f67-1b63b94194cc,Use density measures from the chemistry materi...,6,3 times
16,5d0080cb-90d7-4712-bc33-848150e917d3,What was the volume in m^3 of the fish bag tha...,0.1777,0.003
17,bec74516-02fc-48dc-b202-55e78d0e17cf,What is the average number of pre-2020 works o...,26.4,"""average number"""
18,a1e91b78-d3d8-4675-bb8d-62741b4b68a6,In the video https://www.youtube.com/watch?v=L...,3,12
19,46719c30-f4c3-4cad-be07-d5cb21eee6bb,Of the authors (First M. Last) that worked on ...,Mapping Human Oriented Information to Software...,"""Pie Menus or Linear Menus, Which Is Better?"""
20,df6561b2-7ee5-4540-baab-5095f742716a,When you take the average of the standard popu...,17.056,1.000

In [79]:
import pandas as pd, json
from pathlib import Path

path = Path("../results/unified_baseline/mmlu_pro/vanilla/gpt_4o_mini")

df = pd.read_parquet(path / "responses.parquet")
with open(path / "metrics.json", "r") as f:
    metrics = json.load(f)

display(df.head())
print(metrics)

,query_id,dataset,modality,model,query,ground_truth,predicted_answer,is_correct,reasoning_trace,tool_trace,...,completion_tokens,total_tokens,cost_usd,latency_s,error_type,error_message,system_prompt_version,user_prompt_version,prompt_hash,metadata
0,70,mmlu_pro,vanilla,gpt-4o-mini,"Typical advertising regulatory bodies suggest,...",I,I,True,None,None,...,1,211,0.000032,1.329,None,None,v1,v1,a06e830148bb777c3f49499f90678770a1b15789e9c353...,{'subject': 'business'}
1,71,mmlu_pro,vanilla,gpt-4o-mini,Managers are entrusted to run the company in t...,F,F,True,None,None,...,1,228,0.000035,0.566,None,None,v1,v1,039a36924ef0a6947503a701a308ef239a66a65e96eafd...,{'subject': 'business'}
2,72,mmlu_pro,vanilla,gpt-4o-mini,There are two main issues associated with ____...,J,D,False,None,None,...,1,252,0.000038,0.498,None,None,v1,v1,f1e13a63a8286ed11e6fc3de30dff080333c767bb77df1...,{'subject': 'business'}
3,73,mmlu_pro,vanilla,gpt-4o-mini,_______ locate morality beyond the sphere of r...,C,H,False,None,None,...,1,147,0.000022,1.176,None,None,v1,v1,af0a542d47198c0e99eef1f69282c5ff48d72de6f06472...,{'subject': 'business'}
4,74,mmlu_pro,vanilla,gpt-4o-mini,Some of key differences between Islamic finan...,G,B,False,None,None,...,1,246,0.000037,0.494,None,None,v1,v1,a24bbf824e6f65540807630732c358276dcbc74d96df1d...,{'subject': 'business'}

{'dataset': 'mmlu_pro', 'modality': 'vanilla', 'model': 'gpt-4o-mini', 'system_prompt_version': 'v1', 'user_prompt_version': 'v1', 'prompt_hash': 'a06e830148bb777c3f49499f90678770a1b15789e9c35373158547617283e41c', 'total_queries': 10, 'correct_queries': 7, 'accuracy': 0.7, 'total_prompt_tokens': 1881, 'total_completion_tokens': 10, 'total_tokens': 1891, 'avg_tokens_per_query': 189.1, 'total_cost_usd': 0.000288, 'avg_latency_s': 0.754, 'p50_latency_s': 0.612, 'p95_latency_s': 1.26, 'error_count': 0, 'error_rate': 0.0, 'avg_reasoning_steps': None, 'avg_tool_calls': None, 'metadata': {}}

In [82]:
row = df.iloc[0]
print("query_id:", row["query_id"])
print("\nQUERY:\n")
print(row["query"])
print("\nGROUND_TRUTH:", row["ground_truth"])
print("PREDICTED:", row["predicted_answer"])

query_id: 70

QUERY:

Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unnecessary ________ or _____, and must not cause _______ offence.

GROUND_TRUTH: I
PREDICTED: I

In [83]:
import pandas as pd
src = pd.read_parquet("../datasets/processed/mmlu_pro.parquet")  # adjust if needed

r = src[src["id"].astype(str) == "70"].iloc[0]
print("Question:\n", r["query"] if "query" in src.columns else r["question"])
print("\nOptions:\n", r["options"])

Question:
 Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unnecessary ________ or _____, and must not cause _______ offence.

Options:
 ['Safe practices, Fear, Jealousy, Trivial'
 'Unsafe practices, Distress, Joy, Trivial'
 'Safe practices, Wants, Jealousy, Trivial'
 'Safe practices, Distress, Fear, Trivial'
 'Unsafe practices, Wants, Jealousy, Serious'
 'Safe practices, Distress, Jealousy, Serious'
 'Safe practices, Wants, Fear, Serious'
 'Unsafe practices, Wants, Fear, Trivial'
 'Unsafe practices, Distress, Fear, Serious']

In [84]:
import pandas as pd
from baselines.prompt_resolver import resolve_prompts

# 1) load run output row (already generated)
out_df = pd.read_parquet("../results/unified_baseline/mmlu_pro/vanilla/gpt_4o_mini/responses.parquet")
row = out_df[out_df["query_id"].astype(str) == "70"].iloc[0]   # change id

# 2) load source MMLU row to get options
src_df = pd.read_parquet("../datasets/processed/mmlu_pro.parquet")  # adjust path if needed
src_row = src_df[src_df["id"].astype(str) == str(row["query_id"])].iloc[0]

raw_options = src_row.get("options", "")
if isinstance(raw_options, list):
    options_text = "\n".join(f"{chr(65+i)}. {opt}" for i, opt in enumerate(raw_options))
elif hasattr(raw_options, "tolist") and not isinstance(raw_options, (str, bytes)):
    v = raw_options.tolist()
    if isinstance(v, list):
        options_text = "\n".join(f"{chr(65+i)}. {opt}" for i, opt in enumerate(v))
    else:
        options_text = "" if pd.isna(v) else str(v)
else:
    options_text = "" if pd.isna(raw_options) else str(raw_options)

# 3) rebuild prompts exactly like runner does
resolved = resolve_prompts(
    modality="vanilla",
    dataset="mmlu_pro",
    model_name="gpt-4o-mini",
    system_values={
        "model_name": "gpt-4o-mini",
        "output_contract": "Return final answer only.",
    },
    user_values={
        "dataset": "mmlu_pro",
        "query": row["query"],
        "options": options_text,
    },
)

print("=== SYSTEM PROMPT ===\n")
print(resolved.system_prompt)
print("\n=== USER PROMPT (sent to model) ===\n")
print(resolved.user_prompt)

=== SYSTEM PROMPT ===

You are a multiple-choice QA assistant.
Return ONLY one option letter (A-J).
No explanation.
Output contract: Return final answer only.
Model: gpt-4o-mini

=== USER PROMPT (sent to model) ===

Dataset: mmlu_pro
Question: Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unnecessary ________ or _____, and must not cause _______ offence.
Options:
A. Safe practices, Fear, Jealousy, Trivial
B. Unsafe practices, Distress, Joy, Trivial
C. Safe practices, Wants, Jealousy, Trivial
D. Safe practices, Distress, Fear, Trivial
E. Unsafe practices, Wants, Jealousy, Serious
F. Safe practices, Distress, Jealousy, Serious
G. Safe practices, Wants, Fear, Serious
H. Unsafe practices, Wants, Fear, Trivial
I. Unsafe practices, Distress, Fear, Serious
Return one option letter.

In [81]:
print(df.loc[0, "query"])

Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unnecessary ________ or _____, and must not cause _______ offence.

In [80]:
df['query'].iloc[0]

'Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unnecessary ________ or _____, and must not cause _______ offence.'

In [75]:
import pandas as pd
from pathlib import Path

path = Path("../results/unified_baseline/mmlu_pro/vanilla/gpt_4o_mini/responses.parquet")
df = pd.read_parquet(path)

# Overall accuracy
print("Accuracy:", df["is_correct"].mean())
print("Correct/Total:", int(df["is_correct"].sum()), "/", len(df))

# See correct rows
display(df[df["is_correct"] == True][["query_id","query","ground_truth","predicted_answer"]].head())

# See incorrect rows
display(df[df["is_correct"] == False][["query_id","query","ground_truth","predicted_answer"]].head(20))

Accuracy: 0.7
Correct/Total: 7 / 10

,query_id,query,ground_truth,predicted_answer
0,70,"Typical advertising regulatory bodies suggest,...",I,I
1,71,Managers are entrusted to run the company in t...,F,F
5,75,Which of the following are the three broad gr...,A,A
6,76,Pine and Gilmore (1999) derive four distinct ...,D,D
7,77,Which type of research methods are designed t...,J,J

,query_id,query,ground_truth,predicted_answer
2,72,There are two main issues associated with ____...,J,D
3,73,_______ locate morality beyond the sphere of r...,C,H
4,74,Some of key differences between Islamic finan...,G,B

In [78]:
df["query"].iloc[1]

'Managers are entrusted to run the company in the best interest of ________. Specifically, they have a duty to act for the benefit of the company, as well as a duty of ________ and of _______.'

### math

In [95]:

PATH = '../datasets/processed/math_hard.parquet'
df   = pd.read_parquet(PATH)

print(f'Shape  : {df.shape[0]:,} rows × {df.shape[1]} columns')
print(f'Columns: {df.columns.tolist()}')

Shape  : 1,205 rows × 8 columns
Columns: ['id', 'query', 'answer', 'level', 'type', 'solution', 'solution_length', 'has_figure']

In [96]:
df.head()

,id,query,answer,level,type,solution,solution_length,has_figure
0,math_0000,How many square units are in the region satisf...,4.5,Level 5,Algebra,The graph of the two inequalities is shown bel...,946,False
1,math_0001,"When Lauren was born on January 1, 1990, her g...",1160,Level 5,Algebra,"The annual interest rate is 7.5 percent, so ea...",266,False
2,math_0002,Chris labels every lattice point in the coordi...,12,Level 5,Algebra,"Consider the point $(x,y)$. Then, he labels th...",947,False
3,math_0003,An airplane climbs 100 feet during the first s...,15,Level 5,Algebra,"After $t$ seconds, the airplane's altitude (in...",345,False
4,math_0004,Define $f(x)=\frac{1+x}{1-x}$ and $g(x)=\frac{...,4,Level 5,Algebra,Define a new function $h(x)$ so that $h(x)=g(f...,530,False

In [104]:
import pandas as pd
from pathlib import Path

# 1) check source math_hard file actually used
src = pd.read_parquet("../datasets/processed/math_hard.parquet")  # adjust if needed
print(src.columns.tolist())
display(src[["id","answer","solution"]].head(3))

['id', 'query', 'answer', 'level', 'type', 'solution', 'solution_length', 'has_figure']

          id answer                                           solution
0  math_0000    4.5  The graph of the two inequalities is shown bel...
1  math_0001   1160  The annual interest rate is 7.5 percent, so ea...
2  math_0002     12  Consider the point $(x,y)$. Then, he labels th...

,query_id,query,ground_truth,predicted_answer
0,math_0000,How many square units are in the region satisf...,4.5,4.5
1,math_0001,"When Lauren was born on January 1, 1990, her g...",1160,"$1,157"
2,math_0002,Chris labels every lattice point in the coordi...,12,12
3,math_0003,An airplane climbs 100 feet during the first s...,15,12
4,math_0004,Define $f(x)=\frac{1+x}{1-x}$ and $g(x)=\frac{...,4,The final answer is \( -\frac{1}{2} \).
5,math_0005,"Given that the point $(8,8)$ is on the graph o...",36,16
6,math_0006,Bob can travel $m$ miles in $h$ hours on his b...,\frac{h^2,\(\frac{h^2}{m}\)
7,math_0007,"Given that the point $(4,7)$ is on the graph o...",10,11
8,math_0008,Find the domain of the function $f(x)=\sqrt{\s...,"(-\infty,-5]\cup[5,\infty)",Domain: \( x \leq -4 \) or \( x \geq 4 \)
9,math_0009,Evaluate the infinite geometric series: $$1-\f...,\frac{7,\(\frac{7}{9}\)

,id,query,answer,solution
0,math_0000,How many square units are in the region satisf...,4.5,The graph of the two inequalities is shown bel...
1,math_0001,"When Lauren was born on January 1, 1990, her g...",1160,"The annual interest rate is 7.5 percent, so ea..."
2,math_0002,Chris labels every lattice point in the coordi...,12,"Consider the point $(x,y)$. Then, he labels th..."
3,math_0003,An airplane climbs 100 feet during the first s...,15,"After $t$ seconds, the airplane's altitude (in..."
4,math_0004,Define $f(x)=\frac{1+x}{1-x}$ and $g(x)=\frac{...,4,Define a new function $h(x)$ so that $h(x)=g(f...
5,math_0005,"Given that the point $(8,8)$ is on the graph o...",36,"Given that $(8,8)$ is on the graph of $y=\frac..."
6,math_0006,Bob can travel $m$ miles in $h$ hours on his b...,\frac{h^2}{m},"Since Bob travels $m$ miles in $h$ hours, he t..."
7,math_0007,"Given that the point $(4,7)$ is on the graph o...",10,"Given that $(4,7)$ is on the graph of $y=3f\le..."
8,math_0008,Find the domain of the function $f(x)=\sqrt{\s...,"(-\infty,-5]\cup[5,\infty)",Since we know that the terms inside any square...
9,math_0009,Evaluate the infinite geometric series: $$1-\f...,\frac{7}{9},The series has first term $1$ and common ratio...

Missing answers: 0

In [111]:
import pandas as pd
df = pd.read_parquet("../datasets/processed/math_hard.parquet")
print(df["answer_extraction_method"].value_counts(dropna=False))
display(df[["id","answer","answer_extraction_method"]].head(20))

answer_extraction_method
boxed    1205
Name: count, dtype: int64

           id                      answer answer_extraction_method
0   math_0000                         4.5                    boxed
1   math_0001                        1160                    boxed
2   math_0002                          12                    boxed
3   math_0003                          15                    boxed
4   math_0004                           4                    boxed
5   math_0005                          36                    boxed
6   math_0006               \frac{h^2}{m}                    boxed
7   math_0007                          10                    boxed
8   math_0008  (-\infty,-5]\cup[5,\infty)                    boxed
9   math_0009                 \frac{7}{9}                    boxed
10  math_0010               -\frac{35}{9}                    boxed
11  math_0011              -\frac{49}{12}                    boxed
12  math_0012                         -42                    boxed
13  math_0013                 \frac{1}{2}                    boxed
14  math_0014       \frac{5\sqrt{42}}{27}                    boxed
15  math_0015                 \frac{5}{4}                    boxed
16  math_0016                       33840                    boxed
17  math_0017                           5                    boxed
18  math_0018                         -48                    boxed
19  math_0019                 \frac{3}{2}                    boxed

In [113]:
import pandas as pd
df = pd.read_parquet("../datasets/processed/math_hard.parquet")
display(df[["id","query","answer","solution"]].head(10))
print("Missing answers:", df["answer"].isna().sum())

,id,query,answer,solution
0,math_0000,How many square units are in the region satisf...,4.5,The graph of the two inequalities is shown bel...
1,math_0001,"When Lauren was born on January 1, 1990, her g...",1160,"The annual interest rate is 7.5 percent, so ea..."
2,math_0002,Chris labels every lattice point in the coordi...,12,"Consider the point $(x,y)$. Then, he labels th..."
3,math_0003,An airplane climbs 100 feet during the first s...,15,"After $t$ seconds, the airplane's altitude (in..."
4,math_0004,Define $f(x)=\frac{1+x}{1-x}$ and $g(x)=\frac{...,4,Define a new function $h(x)$ so that $h(x)=g(f...
5,math_0005,"Given that the point $(8,8)$ is on the graph o...",36,"Given that $(8,8)$ is on the graph of $y=\frac..."
6,math_0006,Bob can travel $m$ miles in $h$ hours on his b...,\frac{h^2}{m},"Since Bob travels $m$ miles in $h$ hours, he t..."
7,math_0007,"Given that the point $(4,7)$ is on the graph o...",10,"Given that $(4,7)$ is on the graph of $y=3f\le..."
8,math_0008,Find the domain of the function $f(x)=\sqrt{\s...,"(-\infty,-5]\cup[5,\infty)",Since we know that the terms inside any square...
9,math_0009,Evaluate the infinite geometric series: $$1-\f...,\frac{7}{9},The series has first term $1$ and common ratio...

Missing answers: 0

In [121]:
import pandas as pd
df_math = pd.read_parquet("../results/unified_baseline/math_hard/vanilla/gpt_4o_mini/responses.parquet")
display(df_math[["query_id","query","ground_truth","predicted_answer"]].head(10))

,query_id,query,ground_truth,predicted_answer
0,math_0000,How many square units are in the region satisf...,4.5,4.5
1,math_0001,"When Lauren was born on January 1, 1990, her g...",1160,"$1,157"
2,math_0002,Chris labels every lattice point in the coordi...,12,12
3,math_0003,An airplane climbs 100 feet during the first s...,15,seconds = 15
4,math_0004,Define $f(x)=\frac{1+x}{1-x}$ and $g(x)=\frac{...,4,The final answer is 12.
5,math_0005,"Given that the point $(8,8)$ is on the graph o...",36,16
6,math_0006,Bob can travel $m$ miles in $h$ hours on his b...,\frac{h^2}{m},\(\frac{h^2}{m}\)
7,math_0007,"Given that the point $(4,7)$ is on the graph o...",10,11
8,math_0008,Find the domain of the function $f(x)=\sqrt{\s...,"(-\infty,-5]\cup[5,\infty)","[4, ∞)"
9,math_0009,Evaluate the infinite geometric series: $$1-\f...,\frac{7}{9},\(\frac{7}{9}\)

In [120]:
import pandas as pd
df = pd.read_parquet("../results/unified_baseline/math_hard/vanilla/gpt_4o_mini/responses.parquet")
display(df.loc[df["query_id"].isin(["math_0006","math_0009"]), ["query_id","ground_truth","predicted_answer","is_correct"]])

    query_id   ground_truth   predicted_answer  is_correct
6  math_0006  \frac{h^2}{m}  \(\frac{h^2}{m}\)        True
9  math_0009    \frac{7}{9}    \(\frac{7}{9}\)        True

In [123]:
import pandas as pd
from pathlib import Path

path = Path("../results/unified_baseline/math_hard/vanilla/gpt_4o_mini/responses.parquet")
df = pd.read_parquet(path)

wrong = df[df["is_correct"] == False].copy()

print("Incorrect:", len(wrong), "/", len(df))
display(
    wrong[["query_id", "query", "ground_truth", "predicted_answer", "is_correct"]]
    .reset_index(drop=True)
)

Incorrect: 264 / 300

,query_id,query,ground_truth,predicted_answer,is_correct
0,math_0001,"When Lauren was born on January 1, 1990, her g...",1160,"$1,157",False
1,math_0004,Define $f(x)=\frac{1+x}{1-x}$ and $g(x)=\frac{...,4,The final answer is \( -\frac{1}{2} \).,False
2,math_0005,"Given that the point $(8,8)$ is on the graph o...",36,16,False
3,math_0007,"Given that the point $(4,7)$ is on the graph o...",10,11,False
4,math_0008,Find the domain of the function $f(x)=\sqrt{\s...,"(-\infty,-5]\cup[5,\infty)","[4, ∞)",False
...,...,...,...,...,...
259,math_0295,When the expression $-2x^2-20x-53$ is written ...,0,-26,False
260,math_0296,How many ways are there to answer a $10$-quest...,968,1024,False
261,math_0297,How many distinguishable ways are there to wri...,96,256,False
262,math_0298,How many ways are there to arrange $6$ beads o...,180,30,False
263,math_0299,In how many ways can 8 people sit around a rou...,960,720,False

In [126]:
import pandas as pd
df_math = pd.read_parquet("../results/unified_baseline/mmlu_pro/vanilla/gpt_4o_mini/responses.parquet")
display(df_math[["query_id","query","ground_truth","predicted_answer"]].head(10))

,query_id,query,ground_truth,predicted_answer
0,70,"Typical advertising regulatory bodies suggest,...",I,I
1,71,Managers are entrusted to run the company in t...,F,F
2,72,There are two main issues associated with ____...,J,D
3,73,_______ locate morality beyond the sphere of r...,C,H
4,74,Some of key differences between Islamic finan...,G,C
5,75,Which of the following are the three broad gr...,A,A
6,76,Pine and Gilmore (1999) derive four distinct ...,D,D
7,77,Which type of research methods are designed t...,J,J
8,78,Where the price is set low relative to the com...,E,E
9,79,"Once a train pulls out of a station, or an aer...",F,F

In [124]:
import pandas as pd
df_math = pd.read_parquet("../results/unified_baseline/swe_bench_verified/vanilla/gpt_4o_mini/responses.parquet")
display(df_math[["query_id","query","ground_truth","predicted_answer"]].head(10))

,query_id,query,ground_truth,predicted_answer
0,astropy__astropy-12907,Modeling's `separability_matrix` does not comp...,diff --git a/astropy/modeling/separable.py b/a...,"Yes, this behavior appears to be a bug in the ..."
1,astropy__astropy-13033,TimeSeries: misleading exception when required...,diff --git a/astropy/timeseries/core.py b/astr...,To resolve the misleading exception when a req...

In [125]:
df_math['predicted_answer'].iloc[0]

'Yes, this behavior appears to be a bug in the `separability_matrix` function when dealing with nested `CompoundModels`. The expected output should maintain the separability of the linear components, but it incorrectly indicates dependence in the nested case.'